<?php include'mainheader.php'; ?>


<style>
	.top-bar{
		margin-top: 100px;
	}
	@media(max-width: 480px){
		.top-bar{
		margin-top: 0px;
	}
	.contact-form-box{
		overflow-x: hidden !important;
	}
	.carrer-img{
		width: 100% !important;
	}
    .blog-img{
        width: 100%;
    }
    
	}
</style>
                <section class="main-banner">
                    <div class="">
                        <div class="top-bar">
                            <div class="col-md-12 bg-container">
                                <div>
                                    <h2 class="text-center" style="line-height: 36px !important;">A Guide to Understanding Vaastu Shastra and its Impact in Home and Property Buying.</h2>
                                </div>
                            </div>
                        </div>
                    </div>
                </section>
                <!-- single-project-section 
				================================================== -->
                <section class="single-project-section">

                    <div class="container">
                        <div class="single-project-content">
                            <div class="row">

                                <!-- <div class="col-md-12 bg-container " style="padding-right: 0px;">
                                    <div>
                                        <h3>A Guide to Understanding Vaastu Shastra and its Impact in Home and Property Buying.</h3>
                                            <p>Give your dreams a shape of reality</p>

                                    </div>

                                </div> -->
                                <div class="col-md-12">
                                    <div style="margin-top: 30px;">
                                        <div class="col-lg-6" style="margin-bottom: 20px;">
                                            <img width="100%" src="images/vastu-370x245.jpg"/>
                                        </div>

                                        <p>
                                            Traditionally, Vaastu Shastra refers to an ancient Hindu system of architecture. During the early days of Indian architecture and planning, this was an efficient way of arranging positive vibe in the construction. Constructors were required to follow a specific design sequence when they were creating a home according to Vaastu principles.</p>

                                            <p>The importance of Vaastu cannot be denied when it comes to major property purchases. Vaastu always strives to help us achieve personal harmony and peace. If you consider these aspects in the property purchases you make, you are likely to attain prosperity, wealth, and peace when you invest your money in Vaastu-compliant properties. As well as that, the corporate property has already demonstrated steady growth in various sectors from mega projects to commercial sectors.
                                        </p>
                                        <h4>Now, why do we have to focus on the Vaastu?</h4>
                                        <p>Vaastu is a science of direction that integrates the five elements of nature and the cosmos, ultimately balancing man, and his surroundings. Known as Panchbhoota science, it unites earth, fire, water, sky, and space and enables enlightenment, happiness, and prosperity.</p>

                                        <h4>Elements Of Vaastu </h4>
                                        <p>According to Vaastu, we need to learn how to harness and balance the beneficial energies that exist in the cosmos to enjoy a state of well-being. In essence, energy is generated by two forces – the five elements and the electro-magnetic energy of earth’s rotation. Earth is the third of the nine planets and possesses panchabhootas, which enable it to support life. While more discoveries are being made about making life possible on other planets, Earth has always been our only home. Regardless of where we live, sunlight, air, and space are available to us and can be shaped according to our needs. In order to fully comprehend design with these five elements, we need to discuss them separately.</p>
                                        
                                       <ul>
                                        <li style="color: #E31E24;font-weight: 600;"> Earth :  </li>
                                        <p>The first and foremost element of nature to exert the greatest amount of energy. You should conduct research on the plot before purchasing it, as everything matters in Vaastu. In Vaastu, site selection plays an important role. Before construction can begin, the soil, plot, site, shape, and size must be inspected. Human lives are influenced in every way by the earth (Prithvi) in Vaastu.</p>
                                        <li style="color: #E31E24;font-weight: 600;"> Water : </li>
                                        <p> Find property agents who understand your specific needs and provide tailored recommendations through targeted advertising and personalized communication.</p>
                                        <li style="color: #E31E24;font-weight: 600;"> Fire :   </li>
                                        <p>The element of fire (Agni) is considered an element of the south-east. Kitchen fires and electrical gadgets should be placed in the south-east of a house. There is no life without light, and the sun is the natural source of light. In addition to thermal power and atomic power, fire is the basis of all sources of energy. For sunlight to be a natural and necessary source of light for humans, there should be proper ventilation.</p>
                                        <li style="color: #E31E24;font-weight: 600;"> Air :  </li>
                                        <p>The air we breathe (Vayu) is a necessity for all of us who live on this planet. The air element is also considered in Vaastu before it is applied. The element of air is associated with the north-west. In addition to oxygen, nitrogen, helium, and carbon dioxide, there are a number of gases in air that make up the earth’s atmosphere. For living beings on this planet, it is important to maintain a balance of different gases, atmospheric pressure, and humidity levels. A good amount of air should enter through the windows and doors according to Vaastu.</p>
                                        <li style="color: #E31E24;font-weight: 600;"> Space : </li>
                                        <p>The sky is never-ending, and our universe is filled with constellations, galaxies, stars, moons, suns, and all nine planets. There is also a term for the universe called ‘Brahmanand’, which means the place of God. There is no denying the importance of space in our lives, and Vaastu provides different directions for making our spaces better. In Indian houses, the middle of the house had an open space. There should be no obstruction to the space in the ashram — it is a brahmasthan that should remain open. Any disruption to the space in the ashram would be detrimental.</p>

                                       
                                       </ul>

                                      
                        
                                  
                                

                                
                            
                                


                        </div>
                    </div>
            
            </section>
            <!-- End single-project-section -->

            <?php include'mainfooter.php'; ?>